trigger:
- master

pool:
  name: 'minturpool'

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'mv-mintur-connection'
    runOptions: 'commands'
    commands: |
      sudo docker compose down
    readyTimeout: '20000'
